### PR TITLE
feat: Allow multiple domains in a single certificate

### PR DESCRIPTION
**Pull request by alemarmed**
This is a follow up of https://github.com/terraform-aws-modules/terraform-aws-acm/pull/137
Credits to @amontalban for the work, I made requested changes and tested the feature.

## Description
This PR allows creating one ACM certificate for multiple domains, which, is useful when using the certificate for CloudFront that only allows one certificate per distribution.

## Motivation and Context
CloudFront does not support multiple ACM certificates, like ALB. Therefore, if you need to support multiple domains in a single CloudFront distribution you would have to create the certificate manually because this module does not support it.

## Breaking Changes
This change should be backward compatible as I added a zones var containing a map with domains and their Route53 zone ID so the validation records are created in the correct Route53 zone.

Additionally, I have updated the tests in examples/complete-dns-validation to allow variables so it was easier for me (and others) to test with my test domains.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

Fixes https://github.com/terraform-aws-modules/terraform-aws-acm/issues/136

### CODE REVIEW

**Comment by alemarmed** [comment]
Hi @antonbabenko, is there a chance of resuming the review that you left on https://github.com/terraform-aws-modules/terraform-aws-acm/pull/137 here?
Thanks.

**Comment by amontalban** [comment]
Thank you @alemarmed for doing this, I totally dropped the ball on the #137 but glad you created this because now I'm needing this again 🤣.

**Comment by amontalban** [comment]
@bryantbiggs any chance you can check this out? Thanks!

**Comment by nicolajv** [comment]
This would be amazing to have, commenting to keep it alive

**Comment by y3ti** [comment]
It would be great to have this feature!

**Comment by Samseppiol** [comment]
Waiting for this. It has been open since March, can a maintainer please review?

**Comment by amontalban** [comment]
@bryantbiggs @antonbabenko any chance you can review/merge this 🙏? Thanks!

**Comment by riptidewave93** [comment]
Another bump to prevent this PR from being stale. Really wish the maintainer would provide feedback here :(

**Review by antonbabenko — APPROVED** [review]
Yes, it works! Thanks to everyone involved.

**Comment by antonbabenko** [comment]
This PR is included in version 5.1.0 :tada:

**Pull request merged**
