### PR TITLE
fix: Wait for correct certificate_arn when validation is enabled

### PR DESCRIPTION
**Pull request by lhelman**
## Description
I'm adding a way to wait for the DNS cert validation to be complete

## Motivation and Context
There is no good way to wait until the certificate is validated, so there is a race condition when trying to use the certificate.
This allows you to wait for it.

A use example would be:
```
resource "aws_lb_listener" "front_end" {
  # [...]
  certificate_arn = "${module.acm.validated_acm_certificate_ar}"
}
```
## Breaking Changes
No breaking changes

## How Has This Been Tested?
I tried using the certificate on an aws_lb_listener. 
Before: Needed 2 applies (first one ends up with error)
After: One apply and everything working

Also, tried using it in an already created cert. It worked.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Hi @lhelman !

You should set `wait_for_validation = true` like here:

https://github.com/terraform-aws-modules/terraform-aws-acm/blob/a8842dc90aab69ae99038bf80bf3f9d8e355d61f/examples/complete-dns-validation/main.tf#L37

**Comment by antonbabenko** [comment]
I don't think there is anything missing, so we can close this PR. Agree?

**Comment by lhelman** [comment]
> Hi @lhelman !
> 
> You should set `wait_for_validation = true` like here:
> 
> https://github.com/terraform-aws-modules/terraform-aws-acm/blob/a8842dc90aab69ae99038bf80bf3f9d8e355d61f/examples/complete-dns-validation/main.tf#L37

No, that doesn't work that way afaik.
I've already set that module parameter (before creating this PR) and it still have issues with the dependencies.

When you set that module parameter, it just calls "aws_acm_certificate_validation", but that doesn't add anything to the dependency graph, you need a way for the resource that will use this certificate to know that the certificate has been validated.

So you need to use the output of the `aws_acm_certificate_validation` resource.

I think my intended change is clearer now.


Please take a look at the documentation of this resource  https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html#dns-validation-with-route-53

```
...

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = ["${aws_route53_record.cert_validation.fqdn}"]
}

resource "aws_lb_listener" "front_end" {
  # [...]
  certificate_arn = "${aws_acm_certificate_validation.cert.certificate_arn}"
}
```

As shown in the documentation, you need the output of the aws_acm_certificate_validation.cert.certificate_arn to be used so the aws_lb_listener "knows" it needs to wait until the certificate is validated.

**Comment by lhelman** [comment]
any chance to review this now @antonbabenko ? (sorry for the noise again)

**Comment by antonbabenko** [comment]
Hi @lhelman !

Thanks for this issue. I wonder why this has not been reported earlier by anyone, I also use this module extensively in various projects.

I will update code in this PR now and merge.

**Comment by antonbabenko** [comment]
[v2.11.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.11.0) has been just released.

**Pull request merged**
