### PR TITLE
feat: validation_allow_overwrite_records variable to allow overwrite records

### PR DESCRIPTION
**Pull request by jvelasquezjs**
Include `validation_allow_overwrite_records` variable to deal with multiple certificates with the same domain name.

### CODE REVIEW

**Comment by jvelasquezjs** [comment]
@antonbabenko 

Please can you have a look into this? Is for terraform 0.11 and is kind of critical for us! Thanks :)

**Comment by antonbabenko** [comment]
wow, 4 upvotes for 5 minutes. Sounds like a mega-blocker! Merging and releasing right away :)

**Comment by jvelasquezjs** [comment]
Amazing @antonbabenko ! 👀 will keep an eye on the releases

**Comment by antonbabenko** [comment]
[v1.4.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v1.4.0) has been just released.

Thank you for this pull-request!

**Pull request merged**
