### PR TITLE
feat: add dns ttl as variable

### PR DESCRIPTION
**Pull request by tomasbackman**
## Description
This is a PR with same changes as in:
https://github.com/terraform-aws-modules/terraform-aws-acm/pull/35
Originally done by @rafaelkonrath

## Motivation and Context
There is a small PR about this already but suggested changes and rebase/merge for it has not been done yet so I redid same, since I have some interest in this =) hopefully not stepping on anyones toes here.

## Breaking Changes
No

## How Has This Been Tested?
Same changes as has been reviewed by @bryantbiggs and more or less accepted then =)

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thank you @tomasbackman - would you mind running the precmomit hook to update the documentation please?

**Comment by tomasbackman** [comment]
@bryantbiggs I guess I can try, but what hook is that? And how do I run it? I don't see any mention of any hook in neither the `contributing guidelines` nor the `readme` so Im not really sure on how..

It sounds like it is about updating the documentations? I guess I could do that manually as well, but yes a tool for it would be nice =)

**Comment by bryantbiggs** [comment]
thanks @tomasbackman - we'll have to take a look at updating the docs for that. you should have seen something show up on your cli when running `git commit`. here is a link to the project we typically use on these modules https://github.com/antonbabenko/pre-commit-terraform - at minimum you just need 
- https://pre-commit.com/#install 
- https://github.com/segmentio/terraform-docs

once those are available on your machine its just a matter of running manually with `pre-commit run -a` or if  you make changes to the codebase and run `git commit` the hook will kick in to fire also

**Comment by bryantbiggs** [comment]
@antonbabenko :+1:

**Comment by antonbabenko** [comment]
Great!

[v2.9.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.9.0) has been released.

**Pull request merged**
