### PR TITLE
feat: Cross-account DNS and ACM resource creation

### PR DESCRIPTION
**Pull request by antonbabenko**
Follow up for #108

Fixes #108

PS: I had no push access to the original fork, so I have created this PR instead.

### CODE REVIEW

**Comment by antonbabenko** [comment]
@dannyibishev Thank you for the initial PR.

**Comment by antonbabenko** [comment]
This PR is included in version 4.1.0 :tada:

**Comment by OneBadSanta** [comment]
I am having difficulty getting an example included in this PR to work

https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/examples/complete-dns-validation/main.tf#L31-L52

When looking at main.tf, i do not see these providers located in resource sections. Am I missing something? How do I use this for cross-account?

Thanks

**Comment by antonbabenko** [comment]
@OneBadSanta `providers` blocks with different aliases (acm and route53) can be declared as shown in README here - https://github.com/terraform-aws-modules/terraform-aws-acm#usage-with-route53-dns-validation-and-separate-aws-providers . In the example you point, both instance of AWS provider are the same (`aws`).

**Comment by OneBadSanta** [comment]
@antonbabenko Thanks for the response. Right. I understand what you're saying. In that the module needs to be split apart in order to use 2 different providers. For me personally, this seems to miss the point of the usefulness of having a module for this purpose. I guess the question how is it possible that example one even works?

https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/examples/complete-dns-validation/main.tf#L13-L52

The resources do not in v4.1.0 do not have multiple providers. There is no mention of aws.acm  and aws.dns, only the global default aws.

```
  providers = {
    aws.acm = aws,
    aws.dns = aws
  }
```

Am I missing something? Does my questions make sense?

Thanks

**Pull request merged**
